export const FETCH_HOME_POKEMONS = 'FETCH_HOME_POKEMONS';
export const FETCH_SELECTED_POKEMON_EVOLUTION = 'FETCH_SELECTED_POKEMON_EVOLUTION';
export const FETCH_SELECTED_POKEMON_DATA = 'FETCH_SELECTED_POKEMON_DATA';
export const FETCH_SELECTED_POKEMON_DATA_LOADING = 'FETCH_SELECTED_POKEMON_DATA_LOADING';
