export const FETCH_HOME_POKEMONS = 'FETCH_HOME_POKEMONS';
export const FETCH_SELECTED_POKEMON_EVOLUTION = 'FETCH_SELECTED_POKEMON_EVOLUTION';
export const FETCH_SELECTED_POKEMON_DATA = 'FETCH_SELECTED_POKEMON_DATA';
export const DATA_LOADING = 'DATA_LOADING';
export const FETCH_ALL_POKEMONS = 'FETCH_ALL_POKEMONS';